services:
  redis:
    image: redis:7-alpine
    container_name: trigger_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  web:
    build: .
    container_name: trigger_web
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped

  worker:
    build: .
    container_name: trigger_worker
    command: celery -A celery_app.celery worker --loglevel=info --concurrency=1 --include=tasks
    volumes:
      - ./api_calls:/app/api_calls
      - ./:/app      
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - EXECUTOR_URL=http://executor:8001/run
    depends_on:
      - redis
      - executor
    restart: unless-stopped

  executor:
    build: .
    container_name: trigger_executor
    command: uvicorn executor:app --host 0.0.0.0 --port 8001
    volumes:
      - ./:/app
    ports:
      - "8001:8001"
    environment:
      - CUSTOM_TIMEOUT_SECONDS=5
      - CUSTOM_CPU_SECONDS=2
      - CUSTOM_MEMORY_MB=100
    depends_on:
      - redis
    restart: unless-stopped

  # client:
  #   build: .
  #   container_name: trigger_client
  #   command: python client.py
  #   volumes:
  #     - ./:/app
  #   environment:
  #     - BASE_URL=http://web:8000
  #   depends_on:
  #     - web
  #   restart: "no"
  #
